# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

D1_2nd <- function(n, f1, A) {
    .Call(`_iNEXT_D1_2nd`, n, f1, A)
}

Dq_2nd <- function(n, f1, A, q) {
    .Call(`_iNEXT_Dq_2nd`, n, f1, A, q)
}

Dq <- function(ifi, n, qs, f1, A) {
    .Call(`_iNEXT_Dq`, ifi, n, qs, f1, A)
}

qDFUN <- function(q, Xi, n) {
    .Call(`_iNEXT_qDFUN`, q, Xi, n)
}

qD_MLE <- function(q, ai) {
    .Call(`_iNEXT_qD_MLE`, q, ai)
}

RTD <- function(x, n, m, q) {
    .Call(`_iNEXT_RTD`, x, n, m, q)
}

RTD_inc <- function(y, nT, t_, q) {
    .Call(`_iNEXT_RTD_inc`, y, nT, t_, q)
}

